name: CC-BY-SA-4.0

on:
  schedule:
    - cron: '20 1 * * *'

jobs:
  run:
    name: Generate CC-BY-SA-4.0 License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: Generate License
        uses: ./
        with:
          path: LICENSE
          type: CC-BY-SA-4.0
          year: 2019
          author: yi_Xu

      - name: Show License
        run: |
          cat LICENSE
